// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: 'f30ef677-64a9-4768-934f-5fbbc0e1ad27',
    name: 'Subscription-1',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: [],
    _eventsCount: '1',
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_BATCH_ACCOUNT'] = 'test1';
  process.env['AZURE_BATCH_ENDPOINT'] = 'https://test1.westus.batch.azure.com';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://test1.westus.batch.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/jobs?api-version=2016-07-01.3.1&timeout=30', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 16 Nov 2016 23:13:14 GMT',
  etag: '0x8D40E762466C16F',
  location: 'https://test1.westus.batch.azure.com/jobs/job-1',
  server: 'Microsoft-HTTPAPI/2.0',
  'request-id': 'c615eac3-f933-497e-aed4-7f413e286c69',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-content-type-options': 'nosniff',
  'client-request-id': '7c4094ea-97c8-4e5f-bfb2-3e353769fc39',
  dataserviceversion: '3.0',
  dataserviceid: 'https://test1.westus.batch.azure.com/jobs/job-1',
  date: 'Wed, 16 Nov 2016 23:13:11 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://test1.westus.batch.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/jobs?api-version=2016-07-01.3.1&timeout=30', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 16 Nov 2016 23:13:14 GMT',
  etag: '0x8D40E762466C16F',
  location: 'https://test1.westus.batch.azure.com/jobs/job-1',
  server: 'Microsoft-HTTPAPI/2.0',
  'request-id': 'c615eac3-f933-497e-aed4-7f413e286c69',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-content-type-options': 'nosniff',
  'client-request-id': '7c4094ea-97c8-4e5f-bfb2-3e353769fc39',
  dataserviceversion: '3.0',
  dataserviceid: 'https://test1.westus.batch.azure.com/jobs/job-1',
  date: 'Wed, 16 Nov 2016 23:13:11 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://test1.westus.batch.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/jobs/helloworld/addtaskcollection?api-version=2016-07-01.3.1', '*')
  .reply(200, "{\r\n  \"odata.metadata\":\"https://test1.westus.batch.azure.com/$metadata#taskaddresult\",\"value\":[\r\n    {\r\n      \"status\":\"Success\",\"taskId\":\"mytask1\",\"eTag\":\"0x8D40E7623B59CDB\",\"lastModified\":\"2016-11-16T23:13:13.4117083Z\",\"location\":\"https://test1.westus.batch.azure.com/jobs/helloworld/tasks/mytask1\"\r\n    },{\r\n      \"status\":\"Success\",\"taskId\":\"mytask2\",\"eTag\":\"0x8D40E7623BBF0C4\",\"lastModified\":\"2016-11-16T23:13:13.453178Z\",\"location\":\"https://test1.westus.batch.azure.com/jobs/helloworld/tasks/mytask2\"\r\n    }\r\n  ]\r\n}", { 'transfer-encoding': 'chunked',
  'content-type': 'application/json;odata=minimalmetadata',
  server: 'Microsoft-HTTPAPI/2.0',
  'request-id': 'dbf4ff62-cf77-437b-a2fb-88755334e08d',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-content-type-options': 'nosniff',
  dataserviceversion: '3.0',
  date: 'Wed, 16 Nov 2016 23:13:12 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://test1.westus.batch.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/jobs/helloworld/addtaskcollection?api-version=2016-07-01.3.1', '*')
  .reply(200, "{\r\n  \"odata.metadata\":\"https://test1.westus.batch.azure.com/$metadata#taskaddresult\",\"value\":[\r\n    {\r\n      \"status\":\"Success\",\"taskId\":\"mytask1\",\"eTag\":\"0x8D40E7623B59CDB\",\"lastModified\":\"2016-11-16T23:13:13.4117083Z\",\"location\":\"https://test1.westus.batch.azure.com/jobs/helloworld/tasks/mytask1\"\r\n    },{\r\n      \"status\":\"Success\",\"taskId\":\"mytask2\",\"eTag\":\"0x8D40E7623BBF0C4\",\"lastModified\":\"2016-11-16T23:13:13.453178Z\",\"location\":\"https://test1.westus.batch.azure.com/jobs/helloworld/tasks/mytask2\"\r\n    }\r\n  ]\r\n}", { 'transfer-encoding': 'chunked',
  'content-type': 'application/json;odata=minimalmetadata',
  server: 'Microsoft-HTTPAPI/2.0',
  'request-id': 'dbf4ff62-cf77-437b-a2fb-88755334e08d',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-content-type-options': 'nosniff',
  dataserviceversion: '3.0',
  date: 'Wed, 16 Nov 2016 23:13:12 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://test1.westus.batch.azure.com:443')
  .get('/jobs/helloworld?api-version=2016-07-01.3.1&timeout=30')
  .reply(200, "{\r\n  \"odata.metadata\":\"https://test1.westus.batch.azure.com/$metadata#jobs/@Element\",\"id\":\"helloworld\",\"url\":\"https://test1.westus.batch.azure.com/jobs/helloworld\",\"eTag\":\"0x8D40E762466C16F\",\"lastModified\":\"2016-11-16T23:13:14.5726319Z\",\"creationTime\":\"2016-11-16T23:13:14.4687837Z\",\"state\":\"active\",\"stateTransitionTime\":\"2016-11-16T23:13:14.5726319Z\",\"priority\":0,\"usesTaskDependencies\":false,\"constraints\":{\r\n    \"maxWallClockTime\":\"P10675199DT2H48M5.4775807S\",\"maxTaskRetryCount\":0\r\n  },\"poolInfo\":{\r\n    \"poolId\":\"xplatTestPool\"\r\n  },\"executionInfo\":{\r\n    \"startTime\":\"2016-11-16T23:13:14.5726319Z\",\"poolId\":\"xplatTestPool\"\r\n  },\"onAllTasksComplete\":\"noaction\",\"onTaskFailure\":\"noaction\"\r\n}", { 'transfer-encoding': 'chunked',
  'content-type': 'application/json;odata=minimalmetadata',
  'last-modified': 'Wed, 16 Nov 2016 23:13:14 GMT',
  etag: '0x8D40E762466C16F',
  server: 'Microsoft-HTTPAPI/2.0',
  'request-id': '7ffa1058-0738-4e55-b970-6ae92fa8837c',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-content-type-options': 'nosniff',
  'client-request-id': 'c9f66de8-958e-4c8b-b15a-7f7e5fc265c8',
  dataserviceversion: '3.0',
  date: 'Wed, 16 Nov 2016 23:13:12 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://test1.westus.batch.azure.com:443')
  .get('/jobs/helloworld?api-version=2016-07-01.3.1&timeout=30')
  .reply(200, "{\r\n  \"odata.metadata\":\"https://test1.westus.batch.azure.com/$metadata#jobs/@Element\",\"id\":\"helloworld\",\"url\":\"https://test1.westus.batch.azure.com/jobs/helloworld\",\"eTag\":\"0x8D40E762466C16F\",\"lastModified\":\"2016-11-16T23:13:14.5726319Z\",\"creationTime\":\"2016-11-16T23:13:14.4687837Z\",\"state\":\"active\",\"stateTransitionTime\":\"2016-11-16T23:13:14.5726319Z\",\"priority\":0,\"usesTaskDependencies\":false,\"constraints\":{\r\n    \"maxWallClockTime\":\"P10675199DT2H48M5.4775807S\",\"maxTaskRetryCount\":0\r\n  },\"poolInfo\":{\r\n    \"poolId\":\"xplatTestPool\"\r\n  },\"executionInfo\":{\r\n    \"startTime\":\"2016-11-16T23:13:14.5726319Z\",\"poolId\":\"xplatTestPool\"\r\n  },\"onAllTasksComplete\":\"noaction\",\"onTaskFailure\":\"noaction\"\r\n}", { 'transfer-encoding': 'chunked',
  'content-type': 'application/json;odata=minimalmetadata',
  'last-modified': 'Wed, 16 Nov 2016 23:13:14 GMT',
  etag: '0x8D40E762466C16F',
  server: 'Microsoft-HTTPAPI/2.0',
  'request-id': '7ffa1058-0738-4e55-b970-6ae92fa8837c',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-content-type-options': 'nosniff',
  'client-request-id': 'c9f66de8-958e-4c8b-b15a-7f7e5fc265c8',
  dataserviceversion: '3.0',
  date: 'Wed, 16 Nov 2016 23:13:12 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://test1.westus.batch.azure.com:443')
  .get('/jobs/helloworld/tasks?api-version=2016-07-01.3.1&timeout=30')
  .reply(200, "{\r\n  \"odata.metadata\":\"https://test1.westus.batch.azure.com/$metadata#tasks\",\"value\":[\r\n    {\r\n      \"id\":\"mytask1\",\"url\":\"https://test1.westus.batch.azure.com/jobs/helloworld/tasks/mytask1\",\"eTag\":\"0x8D40E7623B59CDB\",\"creationTime\":\"2016-11-16T23:13:13.4117083Z\",\"lastModified\":\"2016-11-16T23:13:13.4117083Z\",\"state\":\"active\",\"stateTransitionTime\":\"2016-11-16T23:13:13.4117083Z\",\"commandLine\":\"cmd /c echo hello1\",\"runElevated\":false,\"constraints\":{\r\n        \"maxWallClockTime\":\"P10675199DT2H48M5.4775807S\",\"retentionTime\":\"P10675199DT2H48M5.4775807S\",\"maxTaskRetryCount\":0\r\n      },\"executionInfo\":{\r\n        \"retryCount\":0,\"requeueCount\":0\r\n      }\r\n    },{\r\n      \"id\":\"mytask2\",\"url\":\"https://test1.westus.batch.azure.com/jobs/helloworld/tasks/mytask2\",\"eTag\":\"0x8D40E7623BBF0C4\",\"creationTime\":\"2016-11-16T23:13:13.453178Z\",\"lastModified\":\"2016-11-16T23:13:13.453178Z\",\"state\":\"active\",\"stateTransitionTime\":\"2016-11-16T23:13:13.453178Z\",\"commandLine\":\"cmd /c echo hello2\",\"runElevated\":false,\"constraints\":{\r\n        \"maxWallClockTime\":\"P10675199DT2H48M5.4775807S\",\"retentionTime\":\"P10675199DT2H48M5.4775807S\",\"maxTaskRetryCount\":0\r\n      },\"executionInfo\":{\r\n        \"retryCount\":0,\"requeueCount\":0\r\n      }\r\n    }\r\n  ]\r\n}", { 'transfer-encoding': 'chunked',
  'content-type': 'application/json;odata=minimalmetadata',
  server: 'Microsoft-HTTPAPI/2.0',
  'request-id': '9599b5a6-cb37-4b3a-a71b-6a7f40fb8897',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-content-type-options': 'nosniff',
  'client-request-id': 'f0750346-6ec1-4ae4-9bf2-02c64aadf53b',
  dataserviceversion: '3.0',
  date: 'Wed, 16 Nov 2016 23:13:15 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://test1.westus.batch.azure.com:443')
  .get('/jobs/helloworld/tasks?api-version=2016-07-01.3.1&timeout=30')
  .reply(200, "{\r\n  \"odata.metadata\":\"https://test1.westus.batch.azure.com/$metadata#tasks\",\"value\":[\r\n    {\r\n      \"id\":\"mytask1\",\"url\":\"https://test1.westus.batch.azure.com/jobs/helloworld/tasks/mytask1\",\"eTag\":\"0x8D40E7623B59CDB\",\"creationTime\":\"2016-11-16T23:13:13.4117083Z\",\"lastModified\":\"2016-11-16T23:13:13.4117083Z\",\"state\":\"active\",\"stateTransitionTime\":\"2016-11-16T23:13:13.4117083Z\",\"commandLine\":\"cmd /c echo hello1\",\"runElevated\":false,\"constraints\":{\r\n        \"maxWallClockTime\":\"P10675199DT2H48M5.4775807S\",\"retentionTime\":\"P10675199DT2H48M5.4775807S\",\"maxTaskRetryCount\":0\r\n      },\"executionInfo\":{\r\n        \"retryCount\":0,\"requeueCount\":0\r\n      }\r\n    },{\r\n      \"id\":\"mytask2\",\"url\":\"https://test1.westus.batch.azure.com/jobs/helloworld/tasks/mytask2\",\"eTag\":\"0x8D40E7623BBF0C4\",\"creationTime\":\"2016-11-16T23:13:13.453178Z\",\"lastModified\":\"2016-11-16T23:13:13.453178Z\",\"state\":\"active\",\"stateTransitionTime\":\"2016-11-16T23:13:13.453178Z\",\"commandLine\":\"cmd /c echo hello2\",\"runElevated\":false,\"constraints\":{\r\n        \"maxWallClockTime\":\"P10675199DT2H48M5.4775807S\",\"retentionTime\":\"P10675199DT2H48M5.4775807S\",\"maxTaskRetryCount\":0\r\n      },\"executionInfo\":{\r\n        \"retryCount\":0,\"requeueCount\":0\r\n      }\r\n    }\r\n  ]\r\n}", { 'transfer-encoding': 'chunked',
  'content-type': 'application/json;odata=minimalmetadata',
  server: 'Microsoft-HTTPAPI/2.0',
  'request-id': '9599b5a6-cb37-4b3a-a71b-6a7f40fb8897',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-content-type-options': 'nosniff',
  'client-request-id': 'f0750346-6ec1-4ae4-9bf2-02c64aadf53b',
  dataserviceversion: '3.0',
  date: 'Wed, 16 Nov 2016 23:13:15 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://test1.westus.batch.azure.com:443')
  .delete('/jobs/helloworld?api-version=2016-07-01.3.1&timeout=30')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Microsoft-HTTPAPI/2.0',
  'request-id': '3a1d4a84-9ff6-4688-8ebc-b39be302edfa',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-content-type-options': 'nosniff',
  'client-request-id': '9c797568-21d5-4a81-97ce-daefe261789a',
  dataserviceversion: '3.0',
  date: 'Wed, 16 Nov 2016 23:13:14 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://test1.westus.batch.azure.com:443')
  .delete('/jobs/helloworld?api-version=2016-07-01.3.1&timeout=30')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Microsoft-HTTPAPI/2.0',
  'request-id': '3a1d4a84-9ff6-4688-8ebc-b39be302edfa',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-content-type-options': 'nosniff',
  'client-request-id': '9c797568-21d5-4a81-97ce-daefe261789a',
  dataserviceversion: '3.0',
  date: 'Wed, 16 Nov 2016 23:13:14 GMT',
  connection: 'close' });
 return result; }]];