// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: 'f30ef677-64a9-4768-934f-5fbbc0e1ad27',
    name: 'Subscription-1',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: [],
    _eventsCount: '1',
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_BATCH_ACCOUNT'] = 'test1';
  process.env['AZURE_BATCH_ENDPOINT'] = 'https://test1.westus.batch.azure.com/';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://test1.westus.batch.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/pools?api-version=2016-02-01.3.0&timeout=30', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 17 Oct 2016 22:38:34 GMT',
  etag: '0x8D3F6DE53F76BE8',
  location: 'https://test1.westus.batch.azure.com/pools/testpool1',
  server: 'Microsoft-HTTPAPI/2.0',
  'request-id': '485c50fe-a19a-4e15-bc93-bacdf42b2a96',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'client-request-id': 'fe1264e2-3c2e-40de-93c1-68721f15e2d5',
  dataserviceversion: '3.0',
  dataserviceid: 'https://test1.westus.batch.azure.com/pools/testpool1',
  date: 'Mon, 17 Oct 2016 22:38:34 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://test1.westus.batch.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/pools?api-version=2016-02-01.3.0&timeout=30', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 17 Oct 2016 22:38:34 GMT',
  etag: '0x8D3F6DE53F76BE8',
  location: 'https://test1.westus.batch.azure.com/pools/testpool1',
  server: 'Microsoft-HTTPAPI/2.0',
  'request-id': '485c50fe-a19a-4e15-bc93-bacdf42b2a96',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'client-request-id': 'fe1264e2-3c2e-40de-93c1-68721f15e2d5',
  dataserviceversion: '3.0',
  dataserviceid: 'https://test1.westus.batch.azure.com/pools/testpool1',
  date: 'Mon, 17 Oct 2016 22:38:34 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://test1.westus.batch.azure.com:443')
  .get('/pools/testpool1?api-version=2016-02-01.3.0&timeout=30')
  .reply(200, "{\r\n  \"odata.metadata\":\"https://test1.westus.batch.azure.com/$metadata#pools/@Element\",\"id\":\"testpool1\",\"url\":\"https://test1.westus.batch.azure.com/pools/testpool1\",\"eTag\":\"0x8D3F6DE53F76BE8\",\"lastModified\":\"2016-10-17T22:38:34.1268456Z\",\"creationTime\":\"2016-10-17T22:38:34.1268456Z\",\"state\":\"active\",\"stateTransitionTime\":\"2016-10-17T22:38:34.1268456Z\",\"allocationState\":\"steady\",\"allocationStateTransitionTime\":\"2016-10-17T22:38:34.7597897Z\",\"vmSize\":\"standard_d1\",\"resizeTimeout\":\"PT15M\",\"currentDedicated\":0,\"targetDedicated\":0,\"enableAutoScale\":false,\"enableInterNodeCommunication\":false,\"maxTasksPerNode\":1,\"taskSchedulingPolicy\":{\r\n    \"nodeFillType\":\"Spread\"\r\n  },\"virtualMachineConfiguration\":{\r\n    \"imageReference\":{\r\n      \"publisher\":\"Canonical\",\"offer\":\"UbuntuServer\",\"sku\":\"15.10\",\"version\":\"latest\"\r\n    },\"nodeAgentSKUId\":\"batch.node.debian 8\"\r\n  }\r\n}", { 'transfer-encoding': 'chunked',
  'content-type': 'application/json;odata=minimalmetadata',
  'last-modified': 'Mon, 17 Oct 2016 22:38:34 GMT',
  etag: '0x8D3F6DE53F76BE8',
  server: 'Microsoft-HTTPAPI/2.0',
  'request-id': 'ff96cd40-b3e5-4391-972a-fc7c8d02f0bd',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'client-request-id': 'b722dd74-1579-45de-b28d-8c84cf4d7a79',
  dataserviceversion: '3.0',
  date: 'Mon, 17 Oct 2016 22:38:34 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://test1.westus.batch.azure.com:443')
  .get('/pools/testpool1?api-version=2016-02-01.3.0&timeout=30')
  .reply(200, "{\r\n  \"odata.metadata\":\"https://test1.westus.batch.azure.com/$metadata#pools/@Element\",\"id\":\"testpool1\",\"url\":\"https://test1.westus.batch.azure.com/pools/testpool1\",\"eTag\":\"0x8D3F6DE53F76BE8\",\"lastModified\":\"2016-10-17T22:38:34.1268456Z\",\"creationTime\":\"2016-10-17T22:38:34.1268456Z\",\"state\":\"active\",\"stateTransitionTime\":\"2016-10-17T22:38:34.1268456Z\",\"allocationState\":\"steady\",\"allocationStateTransitionTime\":\"2016-10-17T22:38:34.7597897Z\",\"vmSize\":\"standard_d1\",\"resizeTimeout\":\"PT15M\",\"currentDedicated\":0,\"targetDedicated\":0,\"enableAutoScale\":false,\"enableInterNodeCommunication\":false,\"maxTasksPerNode\":1,\"taskSchedulingPolicy\":{\r\n    \"nodeFillType\":\"Spread\"\r\n  },\"virtualMachineConfiguration\":{\r\n    \"imageReference\":{\r\n      \"publisher\":\"Canonical\",\"offer\":\"UbuntuServer\",\"sku\":\"15.10\",\"version\":\"latest\"\r\n    },\"nodeAgentSKUId\":\"batch.node.debian 8\"\r\n  }\r\n}", { 'transfer-encoding': 'chunked',
  'content-type': 'application/json;odata=minimalmetadata',
  'last-modified': 'Mon, 17 Oct 2016 22:38:34 GMT',
  etag: '0x8D3F6DE53F76BE8',
  server: 'Microsoft-HTTPAPI/2.0',
  'request-id': 'ff96cd40-b3e5-4391-972a-fc7c8d02f0bd',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'client-request-id': 'b722dd74-1579-45de-b28d-8c84cf4d7a79',
  dataserviceversion: '3.0',
  date: 'Mon, 17 Oct 2016 22:38:34 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://test1.westus.batch.azure.com:443')
  .delete('/pools/testpool1?api-version=2016-02-01.3.0&timeout=30')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Microsoft-HTTPAPI/2.0',
  'request-id': 'a6a026e3-cae0-4dd3-ba2e-a6050e17ede3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'client-request-id': 'b906f510-8631-4d78-81b3-60f81866651a',
  dataserviceversion: '3.0',
  date: 'Mon, 17 Oct 2016 22:38:34 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://test1.westus.batch.azure.com:443')
  .delete('/pools/testpool1?api-version=2016-02-01.3.0&timeout=30')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Microsoft-HTTPAPI/2.0',
  'request-id': 'a6a026e3-cae0-4dd3-ba2e-a6050e17ede3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'client-request-id': 'b906f510-8631-4d78-81b3-60f81866651a',
  dataserviceversion: '3.0',
  date: 'Mon, 17 Oct 2016 22:38:34 GMT',
  connection: 'close' });
 return result; }]];